name: build-and-test
on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # ソースファイルのあるフォルダ
  SOURCE_FOLDER: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore /p:EnableWindowsTargeting=true
      working-directory: ${{env.SOURCE_FOLDER}}

    - name: Build
      run: dotnet build ${{env.SOURCE_FOLDER}} --no-restore /p:EnableWindowsTargeting=true
      
    - name: Test
      id: test
      run: dotnet test ${{env.SOURCE_FOLDER}} --no-build --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Find coverage output path
      run: |
        cp $(find . -name "coverage.cobertura.xml") .
  
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '40 100'

    - name: Read coverage-results.md
      id: read_file
      run: |
        content=$(cat code-coverage-results.md)
        content_arr=($content) # 改行区切りの配列に変換
        content_formatted=$(IFS=$'\n'; echo "${content_arr[*]}") # 配列を改行で結合
        echo "::set-output name=content::$content_formatted"

    - name: Slack Notification
      uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: "{\"text\":\"${{ steps.read_file.outputs.content }}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
